server:
  port: 8089

spring:
  application:
    name: config-server

  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}