server:
  port: 8061

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/products,/api/v1/products/**
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/v1/inventory,/api/v1/inventory/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders,/api/v1/orders/**
